version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "fasteragile!"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  tests:
    build: .
    depends_on:
      - db
    environment:
      RAILS_ENV: test
    command: bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake test"
    volumes:
      - .:/app
volumes:
     pgdata:
